#!/usr/bin/env bun
import { createHmac } from 'node:crypto'
import { basename, join, relative, resolve } from 'node:path'

const DEFAULT_BASE_ENV_FILES = ['.env.development', '.env'] as const

type Args = {
	envDir: string | null
	envFile: string | null
	output: string | null
}

export type TargetEnvFile = {
	baseEnvFile: string | null
	outputFile: string
}

function usage(exitCode = 0): never {
	console.log(`Usage: env-local [options]

Generates local Supabase overrides in the local dotenv file that matches
the project env file shape.

Destination selection:
  .env.development exists -> .env.development.local
  .env exists             -> .env.local
  neither exists          -> .env.local

Options:
  --env-dir <path>    Directory containing env files (default: current directory)
  --env-file <file>   Base env file to mirror, for example .env or .env.development
  --output <file>     Explicit local env file to write
  -h, --help          Show help`)
	process.exit(exitCode)
}

function parseArgs(): Args {
	const raw = process.argv.slice(2)
	const args: Args = {
		envDir: null,
		envFile: null,
		output: null,
	}

	for (let i = 0; i < raw.length; i++) {
		const arg = raw[i]

		if (arg === '--env-dir' && raw[i + 1]) {
			args.envDir = raw[++i]
		} else if (arg === '--env-file' && raw[i + 1]) {
			args.envFile = raw[++i]
		} else if (arg === '--output' && raw[i + 1]) {
			args.output = raw[++i]
		} else if (arg === '-h' || arg === '--help') {
			usage()
		} else {
			console.error(`Unknown option: ${arg}`)
			usage(1)
		}
	}

	return args
}

export function localEnvFileNameFor(baseEnvFile: string): string {
	const name = basename(baseEnvFile)
	return name === '.env' ? '.env.local' : `${name}.local`
}

async function fileExists(filePath: string): Promise<boolean> {
	return Bun.file(filePath).exists()
}

async function detectBaseEnvFile(envDir: string): Promise<string | null> {
	for (const envFile of DEFAULT_BASE_ENV_FILES) {
		if (await fileExists(join(envDir, envFile))) return envFile
	}

	return null
}

export async function resolveTargetEnvFile(
	envDir: string,
	options: { envFile?: string | null; output?: string | null } = {},
): Promise<TargetEnvFile> {
	if (options.output) {
		return {
			baseEnvFile: options.envFile ?? null,
			outputFile: resolve(envDir, options.output),
		}
	}

	const baseEnvFile = options.envFile ?? (await detectBaseEnvFile(envDir))
	const outputFileName = baseEnvFile ? localEnvFileNameFor(baseEnvFile) : '.env.local'

	return {
		baseEnvFile,
		outputFile: resolve(envDir, outputFileName),
	}
}

function parseSupabaseEnv(src: string): Record<string, string> {
	const env: Record<string, string> = {}

	for (const line of src.trim().split('\n')) {
		if (!line) continue
		const [key, ...rest] = line.split('=')
		if (!key) continue
		env[key] = rest.join('=').replace(/^"|"$/g, '')
	}

	return env
}

function requireEnv(env: Record<string, string>, key: string): string {
	const value = env[key]
	if (!value) throw new Error(`supabase status output is missing ${key}`)
	return value
}

async function loadSupabaseEnv(): Promise<Record<string, string>> {
	const proc = Bun.spawn(['bunx', 'supabase', 'status', '-o', 'env'], {
		stdout: 'pipe',
		stderr: 'pipe',
	})

	const [stdout, stderr, exitCode] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
		proc.exited,
	])

	if (exitCode !== 0) {
		const detail = stderr.trim()
		throw new Error(
			detail
				? `Local Supabase is not running. Start it with: bun dev:server\n${detail}`
				: 'Local Supabase is not running. Start it with: bun dev:server',
		)
	}

	return parseSupabaseEnv(stdout)
}

export function renderLocalEnv(env: Record<string, string>): string {
	const hookSecret = createHmac('sha256', requireEnv(env, 'JWT_SECRET'))
		.update('send-email-hook')
		.digest('base64')

	return `# ──────────────────────────────────────────────────────────────────────────────
# Local overrides -- auto-generated by env-local
# Points to local Supabase (bunx supabase start)
# ──────────────────────────────────────────────────────────────────────────────

# Vite (exposed to browser via import.meta.env)
VITE_SUPABASE_URL=${requireEnv(env, 'API_URL')}
VITE_SUPABASE_PUBLISHABLE_KEY=${requireEnv(env, 'PUBLISHABLE_KEY')}
VITE_SITE_URL=http://localhost:5173

# Supabase (server-only)
SUPABASE_URL=${requireEnv(env, 'API_URL')}
SUPABASE_ANON_KEY=${requireEnv(env, 'PUBLISHABLE_KEY')}
SUPABASE_SECRET_KEY=${requireEnv(env, 'SECRET_KEY')}
SUPABASE_SERVICE_ROLE_KEY=${requireEnv(env, 'SECRET_KEY')}
SUPABASE_DB_URL=${requireEnv(env, 'DB_URL')}

# Email -- Supabase auth hook
SEND_EMAIL_HOOK_URI=${requireEnv(env, 'API_URL')}/functions/v1/send-email
SEND_EMAIL_HOOK_SECRET=v1,whsec_${hookSecret}
`
}

async function main() {
	const args = parseArgs()
	const rootDir = process.cwd()
	const envDir = args.envDir ? resolve(rootDir, args.envDir) : rootDir

	if (args.envFile && !(await fileExists(resolve(envDir, args.envFile)))) {
		throw new Error(`${args.envFile} not found in ${envDir}`)
	}

	const target = await resolveTargetEnvFile(envDir, {
		envFile: args.envFile,
		output: args.output,
	})
	const env = await loadSupabaseEnv()
	const content = renderLocalEnv(env)

	await Bun.write(target.outputFile, content)
	console.log(`Generated ${relative(rootDir, target.outputFile) || '.'} from local Supabase`)
}

if (import.meta.main) {
	main().catch((error) => {
		console.error(error instanceof Error ? error.message : String(error))
		process.exit(1)
	})
}
