import { afterEach, describe, expect, test } from 'bun:test'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
	localEnvFileNameFor,
	mergeLocalEnvContent,
	parseEnvKeys,
	renderLocalEnv,
	resolveTargetEnvFile,
} from './index'

const tempDirs: string[] = []

async function makeEnvDir(files: string[] = []): Promise<string> {
	const dir = await mkdtemp(join(tmpdir(), 'env-local-'))
	tempDirs.push(dir)

	for (const file of files) {
		await writeFile(join(dir, file), 'PLACEHOLDER=value\n')
	}

	return dir
}

describe('local env target selection', () => {
	afterEach(async () => {
		await Promise.all(
			tempDirs.splice(0).map((dir) => rm(dir, { force: true, recursive: true })),
		)
	})

	test('maps root env files to their matching local overlay', () => {
		expect(localEnvFileNameFor('.env')).toBe('.env.local')
		expect(localEnvFileNameFor('.env.development')).toBe('.env.development.local')
		expect(localEnvFileNameFor('.env.production')).toBe('.env.production.local')
	})

	test('prefers .env.development when both base env files exist', async () => {
		const envDir = await makeEnvDir(['.env', '.env.development'])
		const target = await resolveTargetEnvFile(envDir)

		expect(target.baseEnvFile).toBe('.env.development')
		expect(target.outputFile).toBe(join(envDir, '.env.development.local'))
	})

	test('uses .env.local when the project only has .env', async () => {
		const envDir = await makeEnvDir(['.env'])
		const target = await resolveTargetEnvFile(envDir)

		expect(target.baseEnvFile).toBe('.env')
		expect(target.outputFile).toBe(join(envDir, '.env.local'))
	})

	test('falls back to .env.local when no base env file exists', async () => {
		const envDir = await makeEnvDir()
		const target = await resolveTargetEnvFile(envDir)

		expect(target.baseEnvFile).toBeNull()
		expect(target.outputFile).toBe(join(envDir, '.env.local'))
	})

	test('allows an explicit output file', async () => {
		const envDir = await makeEnvDir(['.env.development'])
		const target = await resolveTargetEnvFile(envDir, {
			output: '.env.local',
		})

		expect(target.baseEnvFile).toBe('.env.development')
		expect(target.outputFile).toBe(join(envDir, '.env.local'))
	})
})

describe('local env generation shape', () => {
	test('parses only env variable keys from the base file', () => {
		const keys = parseEnvKeys(`# Commented values are ignored
VITE_SUPABASE_URL=placeholder
export SUPABASE_DB_URL=placeholder
# SEND_EMAIL_HOOK_SECRET=placeholder
`)

		expect(keys).toEqual(new Set(['VITE_SUPABASE_URL', 'SUPABASE_DB_URL']))
	})

	test('renders only variables that exist in the base file', () => {
		const content = renderLocalEnv(
			{
				API_URL: 'LOCAL_API',
				DB_URL: 'LOCAL_DB',
				PUBLISHABLE_KEY: 'LOCAL_PUBLISHABLE',
				SECRET_KEY: 'LOCAL_SECRET',
			},
			{
				allowedKeys: new Set(['VITE_SUPABASE_URL', 'SUPABASE_DB_URL']),
			},
		)

		expect(content).toContain('VITE_SUPABASE_URL=LOCAL_API')
		expect(content).toContain('SUPABASE_DB_URL=LOCAL_DB')
		expect(content).not.toContain('VITE_SUPABASE_PUBLISHABLE_KEY')
		expect(content).not.toContain('SEND_EMAIL_HOOK_URI')
		expect(content).not.toContain('SEND_EMAIL_HOOK_SECRET')
		expect(content).not.toContain('# Email -- Supabase auth hook')
	})
})

describe('local env content merge', () => {
	const generatedContent = `# env-local:start
# Local overrides -- auto-generated by env-local
VITE_SUPABASE_URL=LOCAL_API
VITE_SITE_URL=http://localhost:5173
SUPABASE_URL=LOCAL_API
# env-local:end
`

	test('preserves user-created variables below the generated section', () => {
		const existingContent = `${generatedContent}
# App-specific settings
APP_MODE=local
CUSTOM_FLAG=true
`

		const merged = mergeLocalEnvContent(generatedContent, existingContent)

		expect(merged).toContain('# User-created local overrides -- preserved by env-local')
		expect(merged).toContain('# App-specific settings\nAPP_MODE=local\nCUSTOM_FLAG=true')
	})

	test('replaces stale generated values from legacy files', () => {
		const existingContent = `# Local overrides -- auto-generated by env-local
VITE_SUPABASE_URL=OLD_LOCAL_API
SUPABASE_URL=OLD_LOCAL_API

APP_MODE=local
`

		const merged = mergeLocalEnvContent(generatedContent, existingContent)

		expect(merged).toContain('VITE_SUPABASE_URL=LOCAL_API')
		expect(merged).toContain('SUPABASE_URL=LOCAL_API')
		expect(merged).not.toContain('OLD_LOCAL_API')
		expect(merged).toContain('APP_MODE=local')
	})

	test('keeps explicit user overrides outside a marked generated section', () => {
		const existingContent = `${generatedContent}
VITE_SITE_URL=http://localhost:3000
`

		const merged = mergeLocalEnvContent(generatedContent, existingContent)

		expect(merged).toContain('VITE_SITE_URL=http://localhost:5173')
		expect(merged).toContain('VITE_SITE_URL=http://localhost:3000')
		expect(merged.trimEnd().endsWith('VITE_SITE_URL=http://localhost:3000')).toBe(true)
	})

	test('keeps explicit user overrides appended after a legacy generated block', () => {
		const existingContent = `# Local overrides -- auto-generated by env-local
VITE_SITE_URL=http://localhost:5173
SEND_EMAIL_HOOK_SECRET=OLD_HOOK_SECRET

VITE_SITE_URL=http://localhost:3000
`

		const merged = mergeLocalEnvContent(generatedContent, existingContent)

		expect(merged).toContain('VITE_SITE_URL=http://localhost:5173')
		expect(merged).toContain('VITE_SITE_URL=http://localhost:3000')
		expect(merged.trimEnd().endsWith('VITE_SITE_URL=http://localhost:3000')).toBe(true)
	})

	test('does not duplicate the preserved section on repeated runs', () => {
		const once = mergeLocalEnvContent(generatedContent, `${generatedContent}
APP_MODE=local
`)
		const twice = mergeLocalEnvContent(generatedContent, once)

		expect(twice.match(/User-created local overrides/g)?.length).toBe(1)
		expect(twice.match(/APP_MODE=local/g)?.length).toBe(1)
	})

	test('can replace the output wholesale when preservation is disabled', () => {
		const existingContent = `${generatedContent}
APP_MODE=local
`

		const merged = mergeLocalEnvContent(generatedContent, existingContent, {
			preserveUserContent: false,
		})

		expect(merged).toBe(generatedContent)
		expect(merged).not.toContain('APP_MODE=local')
	})
})
