#!/usr/bin/env bun
import { cac } from 'cac'
import { createHmac } from 'node:crypto'
import { basename, join, relative, resolve } from 'node:path'

import { banner, printVersion, readPackageVersion } from './cli-kit'

const DEFAULT_BASE_ENV_FILES = ['.env.development', '.env'] as const
const GENERATED_SECTION_START = '# env-local:start'
const GENERATED_SECTION_END = '# env-local:end'
const USER_SECTION_HEADER = '# User-created local overrides -- preserved by env-local'
const GENERATED_ENV_KEYS = new Set([
	'VITE_SUPABASE_URL',
	'VITE_SUPABASE_PUBLISHABLE_KEY',
	'VITE_SITE_URL',
	'SUPABASE_URL',
	'SUPABASE_ANON_KEY',
	'SUPABASE_SECRET_KEY',
	'SUPABASE_SERVICE_ROLE_KEY',
	'SUPABASE_DB_URL',
	'SEND_EMAIL_HOOK_URI',
	'SEND_EMAIL_HOOK_SECRET',
])
const GENERATED_COMMENT_LINES = new Set([
	'# ──────────────────────────────────────────────────────────────────────────────',
	'# Local overrides -- auto-generated by env-local',
	'# Points to local Supabase (bunx supabase start)',
	'# Vite (exposed to browser via import.meta.env)',
	'# Supabase (server-only)',
	'# Email -- Supabase auth hook',
	GENERATED_SECTION_START,
	GENERATED_SECTION_END,
	USER_SECTION_HEADER,
])

type Args = {
	envDir: string | null
	envFile: string | null
	force: boolean
	output: string | null
	print: boolean
}

export type TargetEnvFile = {
	baseEnvFile: string | null
	outputFile: string
}

type LocalEnvEntry = {
	key: string
	value: () => string
}

type LocalEnvSection = {
	header: string
	entries: LocalEnvEntry[]
}

function createCli() {
	const cli = cac('env-local')
	cli.usage('[options]')
	cli.option('--env-dir <path>', 'Directory containing env files (default: current directory)')
	cli.option('--env-file <file>', 'Base env file to mirror')
	cli.option('--output <file>', 'Explicit local env file to write')
	cli.option('--print', 'Print generated overlay to stdout instead of writing')
	cli.option('--force', 'Overwrite the output file instead of preserving user content')
	cli.option('-v, --version', 'Show version')
	cli.example('env-local')
	cli.example('env-local --env-file .env')
	cli.example('env-local --print')
	cli.help()
	return cli
}

function printUsageAndExit(message: string): never {
	console.error(message)
	createCli().outputHelp()
	process.exit(1)
}

function validateRawOptions(raw: string[]): void {
	const booleanFlags = new Set([
		'--print',
		'--force',
		'--version',
		'-v',
		'--help',
		'-h',
	])
	const valueFlags = new Set(['--env-dir', '--env-file', '--output'])

	for (let index = 0; index < raw.length; index++) {
		const arg = raw[index]
		if (!arg.startsWith('-')) {
			printUsageAndExit(`Unexpected argument: ${arg}`)
		}

		const [flag] = arg.split('=')
		if (booleanFlags.has(flag)) {
			if (arg.includes('=')) printUsageAndExit(`${flag} does not accept a value`)
			continue
		}

		if (valueFlags.has(flag)) {
			if (arg.includes('=')) continue
			const next = raw[index + 1]
			if (!next || next.startsWith('-')) {
				printUsageAndExit(`${flag} requires a value`)
			}
			index++
			continue
		}

		printUsageAndExit(`Unknown option: ${flag}`)
	}
}

function readOptionValue(
	options: Record<string, unknown>,
	name: string,
): string | null {
	const value = options[name]
	return typeof value === 'string' && value.trim() ? value : null
}

function parseArgs(version: string): Args | null {
	validateRawOptions(process.argv.slice(2))

	const cli = createCli()
	const parsed = cli.parse(process.argv, { run: false })
	const options = parsed.options

	if (options.help || options.h) return null
	if (options.version || options.v) {
		printVersion('env-local', version)
		return null
	}

	if (parsed.args.length > 0) {
		printUsageAndExit(`Unexpected argument: ${parsed.args[0]}`)
	}

	return {
		envDir: readOptionValue(options, 'envDir'),
		envFile: readOptionValue(options, 'envFile'),
		force: Boolean(options.force),
		output: readOptionValue(options, 'output'),
		print: Boolean(options.print),
	}
}

export function localEnvFileNameFor(baseEnvFile: string): string {
	const name = basename(baseEnvFile)
	return name === '.env' ? '.env.local' : `${name}.local`
}

async function fileExists(filePath: string): Promise<boolean> {
	return Bun.file(filePath).exists()
}

async function detectBaseEnvFile(envDir: string): Promise<string | null> {
	for (const envFile of DEFAULT_BASE_ENV_FILES) {
		if (await fileExists(join(envDir, envFile))) return envFile
	}

	return null
}

export async function resolveTargetEnvFile(
	envDir: string,
	options: { envFile?: string | null; output?: string | null } = {},
): Promise<TargetEnvFile> {
	const baseEnvFile = options.envFile ?? (await detectBaseEnvFile(envDir))

	if (options.output) {
		return {
			baseEnvFile,
			outputFile: resolve(envDir, options.output),
		}
	}

	const outputFileName = baseEnvFile ? localEnvFileNameFor(baseEnvFile) : '.env.local'

	return {
		baseEnvFile,
		outputFile: resolve(envDir, outputFileName),
	}
}

function parseSupabaseEnv(src: string): Record<string, string> {
	const env: Record<string, string> = {}

	for (const line of src.trim().split('\n')) {
		if (!line) continue
		const [key, ...rest] = line.split('=')
		if (!key) continue
		env[key] = rest.join('=').replace(/^"|"$/g, '')
	}

	return env
}

export function parseEnvKeys(src: string): Set<string> {
	const keys = new Set<string>()

	for (const line of src.split(/\r?\n/)) {
		const key = envKeyFromLine(line)
		if (key) keys.add(key)
	}

	return keys
}

function requireEnv(env: Record<string, string>, key: string): string {
	const value = env[key]
	if (!value) throw new Error(`supabase status output is missing ${key}`)
	return value
}

async function loadSupabaseEnv(): Promise<Record<string, string>> {
	const proc = Bun.spawn(['bunx', 'supabase', 'status', '-o', 'env'], {
		stdout: 'pipe',
		stderr: 'pipe',
	})

	const [stdout, stderr, exitCode] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
		proc.exited,
	])

	if (exitCode !== 0) {
		const detail = stderr.trim()
		throw new Error(
			detail
				? `Local Supabase is not running. Start it with: bun dev:server\n${detail}`
				: 'Local Supabase is not running. Start it with: bun dev:server',
		)
	}

	return parseSupabaseEnv(stdout)
}

function renderLocalEnvSections(
	env: Record<string, string>,
	allowedKeys: Set<string> | null,
): LocalEnvSection[] {
	const include = (key: string) => !allowedKeys || allowedKeys.has(key)
	const hookSecret = () =>
		createHmac('sha256', requireEnv(env, 'JWT_SECRET'))
			.update('send-email-hook')
			.digest('base64')

	return [
		{
			header: '# Vite (exposed to browser via import.meta.env)',
			entries: [
				{
					key: 'VITE_SUPABASE_URL',
					value: () => requireEnv(env, 'API_URL'),
				},
				{
					key: 'VITE_SUPABASE_PUBLISHABLE_KEY',
					value: () => requireEnv(env, 'PUBLISHABLE_KEY'),
				},
				{
					key: 'VITE_SITE_URL',
					value: () => 'http://localhost:5173',
				},
			],
		},
		{
			header: '# Supabase (server-only)',
			entries: [
				{
					key: 'SUPABASE_URL',
					value: () => requireEnv(env, 'API_URL'),
				},
				{
					key: 'SUPABASE_ANON_KEY',
					value: () => requireEnv(env, 'PUBLISHABLE_KEY'),
				},
				{
					key: 'SUPABASE_SECRET_KEY',
					value: () => requireEnv(env, 'SECRET_KEY'),
				},
				{
					key: 'SUPABASE_SERVICE_ROLE_KEY',
					value: () => requireEnv(env, 'SECRET_KEY'),
				},
				{
					key: 'SUPABASE_DB_URL',
					value: () => requireEnv(env, 'DB_URL'),
				},
			],
		},
		{
			header: '# Email -- Supabase auth hook',
			entries: [
				{
					key: 'SEND_EMAIL_HOOK_URI',
					value: () => `${requireEnv(env, 'API_URL')}/functions/v1/send-email`,
				},
				{
					key: 'SEND_EMAIL_HOOK_SECRET',
					value: () => `v1,whsec_${hookSecret()}`,
				},
			],
		},
	].map((section) => ({
		...section,
		entries: section.entries.filter((entry) => include(entry.key)),
	}))
}

export function renderLocalEnv(
	env: Record<string, string>,
	options: { allowedKeys?: Set<string> | null } = {},
): string {
	const sections = renderLocalEnvSections(env, options.allowedKeys ?? null)
		.filter((section) => section.entries.length > 0)
		.map((section) => {
			const entries = section.entries.map((entry) => `${entry.key}=${entry.value()}`).join('\n')

			return `${section.header}\n${entries}`
		})
		.join('\n\n')

	return `${GENERATED_SECTION_START}
# ──────────────────────────────────────────────────────────────────────────────
# Local overrides -- auto-generated by env-local
# Points to local Supabase (bunx supabase start)
# ──────────────────────────────────────────────────────────────────────────────

${sections}
${GENERATED_SECTION_END}
`
}

function envKeyFromLine(line: string): string | null {
	const trimmed = line.trimStart()
	const assignment = trimmed.startsWith('export ')
		? trimmed.slice('export '.length).trimStart()
		: trimmed
	const match = assignment.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=/)

	return match?.[1] ?? null
}

function trimBlankLines(lines: string[]): string[] {
	const next = [...lines]

	while (next[0]?.trim() === '') next.shift()
	while (next.at(-1)?.trim() === '') next.pop()

	return next
}

function userLinesFromLegacyLocalEnv(existingContent: string): string[] {
	const userLines: string[] = []
	let insideGeneratedSection = false

	for (const line of existingContent.split(/\r?\n/)) {
		const trimmed = line.trim()
		const key = envKeyFromLine(line)

		if (trimmed === '# Local overrides -- auto-generated by env-local') {
			insideGeneratedSection = true
			continue
		}

		if (insideGeneratedSection) {
			if (key === 'SEND_EMAIL_HOOK_SECRET') {
				insideGeneratedSection = false
				continue
			}

			if (
				trimmed === '' ||
				GENERATED_COMMENT_LINES.has(trimmed) ||
				(key && GENERATED_ENV_KEYS.has(key))
			) {
				continue
			}

			userLines.push(line)
			continue
		}

		if (!GENERATED_COMMENT_LINES.has(trimmed)) {
			userLines.push(line)
		}
	}

	return trimBlankLines(userLines)
}

function userLinesFromMarkedLocalEnv(existingContent: string): string[] {
	const lines = existingContent.split(/\r?\n/)
	const userLines: string[] = []
	let insideGeneratedSection = false

	for (const line of lines) {
		const trimmed = line.trim()

		if (trimmed === GENERATED_SECTION_START) {
			insideGeneratedSection = true
			continue
		}

		if (trimmed === GENERATED_SECTION_END) {
			insideGeneratedSection = false
			continue
		}

		if (!insideGeneratedSection && !GENERATED_COMMENT_LINES.has(trimmed)) {
			userLines.push(line)
		}
	}

	return trimBlankLines(userLines)
}

export function mergeLocalEnvContent(
	generatedContent: string,
	existingContent: string | null,
	options: { preserveUserContent?: boolean } = {},
): string {
	if (options.preserveUserContent === false) return generatedContent
	if (!existingContent) return generatedContent

	const hasMarkedGeneratedSection =
		existingContent.includes(GENERATED_SECTION_START) &&
		existingContent.includes(GENERATED_SECTION_END)
	const userLines = hasMarkedGeneratedSection
		? userLinesFromMarkedLocalEnv(existingContent)
		: userLinesFromLegacyLocalEnv(existingContent)

	if (userLines.length === 0) return generatedContent

	return `${generatedContent.trimEnd()}

# ──────────────────────────────────────────────────────────────────────────────
${USER_SECTION_HEADER}
# ──────────────────────────────────────────────────────────────────────────────

${userLines.join('\n').trimEnd()}
`
}

async function main() {
	const version = await readPackageVersion()
	const args = parseArgs(version)
	if (!args) return

	banner('env-local', version, 'Generate local Supabase env overlays', {
		quiet: args.print,
	})

	const rootDir = process.cwd()
	const envDir = args.envDir ? resolve(rootDir, args.envDir) : rootDir

	if (args.envFile && !(await fileExists(resolve(envDir, args.envFile)))) {
		throw new Error(`${args.envFile} not found in ${envDir}`)
	}

	const target = await resolveTargetEnvFile(envDir, {
		envFile: args.envFile,
		output: args.output,
	})
	const env = await loadSupabaseEnv()
	const allowedKeys = target.baseEnvFile
		? parseEnvKeys(await Bun.file(resolve(envDir, target.baseEnvFile)).text())
		: null
	const generatedContent = renderLocalEnv(env, { allowedKeys })

	if (args.print) {
		console.log(generatedContent.trimEnd())
		return
	}

	const existingContent = (await fileExists(target.outputFile))
		? await Bun.file(target.outputFile).text()
		: null
	const content = mergeLocalEnvContent(generatedContent, existingContent, {
		preserveUserContent: !args.force,
	})

	await Bun.write(target.outputFile, content)
	console.log(`Generated ${relative(rootDir, target.outputFile) || '.'} from local Supabase`)
}

if (import.meta.main) {
	main().catch((error) => {
		console.error(error instanceof Error ? error.message : String(error))
		process.exit(1)
	})
}
