name: Release Packages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/npm-publish.yml
